- hosts: plexpi
  become: true

  roles:
    - { role: raspbian, tags: [ 'raspbian' ] }
    - { role: vim, tags: [ 'vim' ] }
    - { role: htop, tags: [ 'htop' ] }
    - { role: win2utf8, tags: [ 'win2utf8' ] }
    - { role: plexmediaserver, tags: [ 'plexmediaserver' ] }
    - { role: plexconnect, tags: [ 'plexconnect' ] }
