---
- name: FILE | Ensure directory exists for PlexConnect cert and keys
  file:
    path: "{{ plexconnect_cert_dir }}"
    state: directory

- name: COMMAND | Generate OpenSSL CSR
  command: openssl req -new -nodes -newkey rsa:2048 -out "{{ plexconnect_cert_path }}" -keyout "{{ plexconnect_cert_dir }}/trailers.key" -x509 -days 7300 -subj "/C=US/CN=trailers.apple.com"
  args:
    creates: "{{ plexconnect_cert_path }}"

- name: COMMAND | Generate self-signed OpenSSL certificate
  command: openssl x509 -in "{{ plexconnect_cert_path }}" -outform der -out "{{ plexconnect_cert_dir }}/trailers.cer"
