---
- name: TEMPLATE | PlexConnect service
  template:
    src: plexconnect.service.j2
    dest: /lib/systemd/system/plexconnect.service
    owner: root
    group: root
    mode: 0644
  notify: daemon-reload

- name: FILE | Symlink for starting PlexConnect service at boot time
  file:
    src: /lib/systemd/system/plexconnect.service
    dest: /etc/systemd/system/multi-user.target.wants/plexconnect.service
    owner: root
    group: root
    state: link

- name: SYSTEMD | Enable PlexConnect service
  systemd:
    name: plexconnect
    enabled: yes
    masked: no

- name: SYSTEMD | Ensure PlexConnect service is started
  systemd:
    state: started
    daemon_reload: yes
    name: plexconnect
